
SUCCESS  = 0
REGISTER = 1
LOGIN 	 = 2
UPLOAD   = 3
DOWNLOAD = 4
CREATEDIR = 5
RENAMEDIR = 6
REMOVEDIR = 7
RENAMEFILE = 8
REMOVEFILE = 9
DIRINFO = 10

FAILEDCREATESOCK = 1000 #Failed to create socket
SENDFAILED		 = 1001 #TCP send failed

USERNOTREGISTER     = 2000
USERUNAUTHENTICATED = 2001